# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AsyncOperation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, operation: str=None):  # noqa: E501
        """AsyncOperation - a model defined in Swagger

        :param operation: The operation of this AsyncOperation.  # noqa: E501
        :type operation: str
        """
        self.swagger_types = {
            'operation': str
        }

        self.attribute_map = {
            'operation': 'operation'
        }

        self._operation = operation

    @classmethod
    def from_dict(cls, dikt) -> 'AsyncOperation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AsyncOperation of this AsyncOperation.  # noqa: E501
        :rtype: AsyncOperation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def operation(self) -> str:
        """Gets the operation of this AsyncOperation.


        :return: The operation of this AsyncOperation.
        :rtype: str
        """
        return self._operation

    @operation.setter
    def operation(self, operation: str):
        """Sets the operation of this AsyncOperation.


        :param operation: The operation of this AsyncOperation.
        :type operation: str
        """

        self._operation = operation
