# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.service import Service
from swagger_server import util


class Catalog(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, services: List[Service]=None):  # noqa: E501
        """Catalog - a model defined in Swagger

        :param services: The services of this Catalog.  # noqa: E501
        :type services: List[Service]
        """
        self.swagger_types = {
            'services': List[Service]
        }

        self.attribute_map = {
            'services': 'services'
        }

        self._services = services

    @classmethod
    def from_dict(cls, dikt) -> 'Catalog':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Catalog of this Catalog.  # noqa: E501
        :rtype: Catalog
        """
        return util.deserialize_model(dikt, cls)

    @property
    def services(self) -> List[Service]:
        """Gets the services of this Catalog.


        :return: The services of this Catalog.
        :rtype: List[Service]
        """
        return self._services

    @services.setter
    def services(self, services: List[Service]):
        """Sets the services of this Catalog.


        :param services: The services of this Catalog.
        :type services: List[Service]
        """

        self._services = services
