# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class LastOperationResource(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, state: str=None, description: str=None, instance_usable: bool=None, update_repeatable: bool=None):  # noqa: E501
        """LastOperationResource - a model defined in Swagger

        :param state: The state of this LastOperationResource.  # noqa: E501
        :type state: str
        :param description: The description of this LastOperationResource.  # noqa: E501
        :type description: str
        :param instance_usable: The instance_usable of this LastOperationResource.  # noqa: E501
        :type instance_usable: bool
        :param update_repeatable: The update_repeatable of this LastOperationResource.  # noqa: E501
        :type update_repeatable: bool
        """
        self.swagger_types = {
            'state': str,
            'description': str,
            'instance_usable': bool,
            'update_repeatable': bool
        }

        self.attribute_map = {
            'state': 'state',
            'description': 'description',
            'instance_usable': 'instance_usable',
            'update_repeatable': 'update_repeatable'
        }

        self._state = state
        self._description = description
        self._instance_usable = instance_usable
        self._update_repeatable = update_repeatable

    @classmethod
    def from_dict(cls, dikt) -> 'LastOperationResource':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LastOperationResource of this LastOperationResource.  # noqa: E501
        :rtype: LastOperationResource
        """
        return util.deserialize_model(dikt, cls)

    @property
    def state(self) -> str:
        """Gets the state of this LastOperationResource.


        :return: The state of this LastOperationResource.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state: str):
        """Sets the state of this LastOperationResource.


        :param state: The state of this LastOperationResource.
        :type state: str
        """
        allowed_values = ["in progress", "succeeded", "failed"]  # noqa: E501
        if state not in allowed_values:
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"
                .format(state, allowed_values)
            )

        self._state = state

    @property
    def description(self) -> str:
        """Gets the description of this LastOperationResource.


        :return: The description of this LastOperationResource.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this LastOperationResource.


        :param description: The description of this LastOperationResource.
        :type description: str
        """

        self._description = description

    @property
    def instance_usable(self) -> bool:
        """Gets the instance_usable of this LastOperationResource.


        :return: The instance_usable of this LastOperationResource.
        :rtype: bool
        """
        return self._instance_usable

    @instance_usable.setter
    def instance_usable(self, instance_usable: bool):
        """Sets the instance_usable of this LastOperationResource.


        :param instance_usable: The instance_usable of this LastOperationResource.
        :type instance_usable: bool
        """

        self._instance_usable = instance_usable

    @property
    def update_repeatable(self) -> bool:
        """Gets the update_repeatable of this LastOperationResource.


        :return: The update_repeatable of this LastOperationResource.
        :rtype: bool
        """
        return self._update_repeatable

    @update_repeatable.setter
    def update_repeatable(self, update_repeatable: bool):
        """Sets the update_repeatable of this LastOperationResource.


        :param update_repeatable: The update_repeatable of this LastOperationResource.
        :type update_repeatable: bool
        """

        self._update_repeatable = update_repeatable
