# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.json_schema_object import JSONSchemaObject
from swagger_server import util


class SchemaParameters(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, parameters: JSONSchemaObject=None):  # noqa: E501
        """SchemaParameters - a model defined in Swagger

        :param parameters: The parameters of this SchemaParameters.  # noqa: E501
        :type parameters: JSONSchemaObject
        """
        self.swagger_types = {
            'parameters': JSONSchemaObject
        }

        self.attribute_map = {
            'parameters': 'parameters'
        }

        self._parameters = parameters

    @classmethod
    def from_dict(cls, dikt) -> 'SchemaParameters':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SchemaParameters of this SchemaParameters.  # noqa: E501
        :rtype: SchemaParameters
        """
        return util.deserialize_model(dikt, cls)

    @property
    def parameters(self) -> JSONSchemaObject:
        """Gets the parameters of this SchemaParameters.


        :return: The parameters of this SchemaParameters.
        :rtype: JSONSchemaObject
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters: JSONSchemaObject):
        """Sets the parameters of this SchemaParameters.


        :param parameters: The parameters of this SchemaParameters.
        :type parameters: JSONSchemaObject
        """

        self._parameters = parameters
