# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.service_binding_schema_object import ServiceBindingSchemaObject
from swagger_server.models.service_instance_schema_object import ServiceInstanceSchemaObject
from swagger_server import util


class SchemasObject(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, service_instance: ServiceInstanceSchemaObject=None, service_binding: ServiceBindingSchemaObject=None):  # noqa: E501
        """SchemasObject - a model defined in Swagger

        :param service_instance: The service_instance of this SchemasObject.  # noqa: E501
        :type service_instance: ServiceInstanceSchemaObject
        :param service_binding: The service_binding of this SchemasObject.  # noqa: E501
        :type service_binding: ServiceBindingSchemaObject
        """
        self.swagger_types = {
            'service_instance': ServiceInstanceSchemaObject,
            'service_binding': ServiceBindingSchemaObject
        }

        self.attribute_map = {
            'service_instance': 'service_instance',
            'service_binding': 'service_binding'
        }

        self._service_instance = service_instance
        self._service_binding = service_binding

    @classmethod
    def from_dict(cls, dikt) -> 'SchemasObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SchemasObject of this SchemasObject.  # noqa: E501
        :rtype: SchemasObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def service_instance(self) -> ServiceInstanceSchemaObject:
        """Gets the service_instance of this SchemasObject.


        :return: The service_instance of this SchemasObject.
        :rtype: ServiceInstanceSchemaObject
        """
        return self._service_instance

    @service_instance.setter
    def service_instance(self, service_instance: ServiceInstanceSchemaObject):
        """Sets the service_instance of this SchemasObject.


        :param service_instance: The service_instance of this SchemasObject.
        :type service_instance: ServiceInstanceSchemaObject
        """

        self._service_instance = service_instance

    @property
    def service_binding(self) -> ServiceBindingSchemaObject:
        """Gets the service_binding of this SchemasObject.


        :return: The service_binding of this SchemasObject.
        :rtype: ServiceBindingSchemaObject
        """
        return self._service_binding

    @service_binding.setter
    def service_binding(self, service_binding: ServiceBindingSchemaObject):
        """Sets the service_binding of this SchemasObject.


        :param service_binding: The service_binding of this SchemasObject.
        :type service_binding: ServiceBindingSchemaObject
        """

        self._service_binding = service_binding
