# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.context import Context
from swagger_server.models.maintenance_info import MaintenanceInfo
from swagger_server.models.service_instance_previous_values import ServiceInstancePreviousValues
from swagger_server import util


class ServiceInstanceUpdateRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, context: Context=None, service_id: str=None, plan_id: str=None, parameters: object=None, previous_values: ServiceInstancePreviousValues=None, maintenance_info: MaintenanceInfo=None):  # noqa: E501
        """ServiceInstanceUpdateRequest - a model defined in Swagger

        :param context: The context of this ServiceInstanceUpdateRequest.  # noqa: E501
        :type context: Context
        :param service_id: The service_id of this ServiceInstanceUpdateRequest.  # noqa: E501
        :type service_id: str
        :param plan_id: The plan_id of this ServiceInstanceUpdateRequest.  # noqa: E501
        :type plan_id: str
        :param parameters: The parameters of this ServiceInstanceUpdateRequest.  # noqa: E501
        :type parameters: object
        :param previous_values: The previous_values of this ServiceInstanceUpdateRequest.  # noqa: E501
        :type previous_values: ServiceInstancePreviousValues
        :param maintenance_info: The maintenance_info of this ServiceInstanceUpdateRequest.  # noqa: E501
        :type maintenance_info: MaintenanceInfo
        """
        self.swagger_types = {
            'context': Context,
            'service_id': str,
            'plan_id': str,
            'parameters': object,
            'previous_values': ServiceInstancePreviousValues,
            'maintenance_info': MaintenanceInfo
        }

        self.attribute_map = {
            'context': 'context',
            'service_id': 'service_id',
            'plan_id': 'plan_id',
            'parameters': 'parameters',
            'previous_values': 'previous_values',
            'maintenance_info': 'maintenance_info'
        }

        self._context = context
        self._service_id = service_id
        self._plan_id = plan_id
        self._parameters = parameters
        self._previous_values = previous_values
        self._maintenance_info = maintenance_info

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceInstanceUpdateRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceInstanceUpdateRequest of this ServiceInstanceUpdateRequest.  # noqa: E501
        :rtype: ServiceInstanceUpdateRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def context(self) -> Context:
        """Gets the context of this ServiceInstanceUpdateRequest.


        :return: The context of this ServiceInstanceUpdateRequest.
        :rtype: Context
        """
        return self._context

    @context.setter
    def context(self, context: Context):
        """Sets the context of this ServiceInstanceUpdateRequest.


        :param context: The context of this ServiceInstanceUpdateRequest.
        :type context: Context
        """

        self._context = context

    @property
    def service_id(self) -> str:
        """Gets the service_id of this ServiceInstanceUpdateRequest.


        :return: The service_id of this ServiceInstanceUpdateRequest.
        :rtype: str
        """
        return self._service_id

    @service_id.setter
    def service_id(self, service_id: str):
        """Sets the service_id of this ServiceInstanceUpdateRequest.


        :param service_id: The service_id of this ServiceInstanceUpdateRequest.
        :type service_id: str
        """
        if service_id is None:
            raise ValueError("Invalid value for `service_id`, must not be `None`")  # noqa: E501

        self._service_id = service_id

    @property
    def plan_id(self) -> str:
        """Gets the plan_id of this ServiceInstanceUpdateRequest.


        :return: The plan_id of this ServiceInstanceUpdateRequest.
        :rtype: str
        """
        return self._plan_id

    @plan_id.setter
    def plan_id(self, plan_id: str):
        """Sets the plan_id of this ServiceInstanceUpdateRequest.


        :param plan_id: The plan_id of this ServiceInstanceUpdateRequest.
        :type plan_id: str
        """

        self._plan_id = plan_id

    @property
    def parameters(self) -> object:
        """Gets the parameters of this ServiceInstanceUpdateRequest.


        :return: The parameters of this ServiceInstanceUpdateRequest.
        :rtype: object
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters: object):
        """Sets the parameters of this ServiceInstanceUpdateRequest.


        :param parameters: The parameters of this ServiceInstanceUpdateRequest.
        :type parameters: object
        """

        self._parameters = parameters

    @property
    def previous_values(self) -> ServiceInstancePreviousValues:
        """Gets the previous_values of this ServiceInstanceUpdateRequest.


        :return: The previous_values of this ServiceInstanceUpdateRequest.
        :rtype: ServiceInstancePreviousValues
        """
        return self._previous_values

    @previous_values.setter
    def previous_values(self, previous_values: ServiceInstancePreviousValues):
        """Sets the previous_values of this ServiceInstanceUpdateRequest.


        :param previous_values: The previous_values of this ServiceInstanceUpdateRequest.
        :type previous_values: ServiceInstancePreviousValues
        """

        self._previous_values = previous_values

    @property
    def maintenance_info(self) -> MaintenanceInfo:
        """Gets the maintenance_info of this ServiceInstanceUpdateRequest.


        :return: The maintenance_info of this ServiceInstanceUpdateRequest.
        :rtype: MaintenanceInfo
        """
        return self._maintenance_info

    @maintenance_info.setter
    def maintenance_info(self, maintenance_info: MaintenanceInfo):
        """Sets the maintenance_info of this ServiceInstanceUpdateRequest.


        :param maintenance_info: The maintenance_info of this ServiceInstanceUpdateRequest.
        :type maintenance_info: MaintenanceInfo
        """

        self._maintenance_info = maintenance_info
