# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.service_binding_endpoint import ServiceBindingEndpoint
from swagger_server.models.service_binding_metadata import ServiceBindingMetadata
from swagger_server.models.service_binding_volume_mount import ServiceBindingVolumeMount
from swagger_server import util


class ServiceBindingResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, metadata: ServiceBindingMetadata=None, credentials: object=None, syslog_drain_url: str=None, route_service_url: str=None, volume_mounts: List[ServiceBindingVolumeMount]=None, endpoints: List[ServiceBindingEndpoint]=None):  # noqa: E501
        """ServiceBindingResponse - a model defined in Swagger

        :param metadata: The metadata of this ServiceBindingResponse.  # noqa: E501
        :type metadata: ServiceBindingMetadata
        :param credentials: The credentials of this ServiceBindingResponse.  # noqa: E501
        :type credentials: object
        :param syslog_drain_url: The syslog_drain_url of this ServiceBindingResponse.  # noqa: E501
        :type syslog_drain_url: str
        :param route_service_url: The route_service_url of this ServiceBindingResponse.  # noqa: E501
        :type route_service_url: str
        :param volume_mounts: The volume_mounts of this ServiceBindingResponse.  # noqa: E501
        :type volume_mounts: List[ServiceBindingVolumeMount]
        :param endpoints: The endpoints of this ServiceBindingResponse.  # noqa: E501
        :type endpoints: List[ServiceBindingEndpoint]
        """
        self.swagger_types = {
            'metadata': ServiceBindingMetadata,
            'credentials': object,
            'syslog_drain_url': str,
            'route_service_url': str,
            'volume_mounts': List[ServiceBindingVolumeMount],
            'endpoints': List[ServiceBindingEndpoint]
        }

        self.attribute_map = {
            'metadata': 'metadata',
            'credentials': 'credentials',
            'syslog_drain_url': 'syslog_drain_url',
            'route_service_url': 'route_service_url',
            'volume_mounts': 'volume_mounts',
            'endpoints': 'endpoints'
        }

        self._metadata = metadata
        self._credentials = credentials
        self._syslog_drain_url = syslog_drain_url
        self._route_service_url = route_service_url
        self._volume_mounts = volume_mounts
        self._endpoints = endpoints

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceBindingResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceBindingResponse of this ServiceBindingResponse.  # noqa: E501
        :rtype: ServiceBindingResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self) -> ServiceBindingMetadata:
        """Gets the metadata of this ServiceBindingResponse.


        :return: The metadata of this ServiceBindingResponse.
        :rtype: ServiceBindingMetadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: ServiceBindingMetadata):
        """Sets the metadata of this ServiceBindingResponse.


        :param metadata: The metadata of this ServiceBindingResponse.
        :type metadata: ServiceBindingMetadata
        """

        self._metadata = metadata

    @property
    def credentials(self) -> object:
        """Gets the credentials of this ServiceBindingResponse.


        :return: The credentials of this ServiceBindingResponse.
        :rtype: object
        """
        return self._credentials

    @credentials.setter
    def credentials(self, credentials: object):
        """Sets the credentials of this ServiceBindingResponse.


        :param credentials: The credentials of this ServiceBindingResponse.
        :type credentials: object
        """

        self._credentials = credentials

    @property
    def syslog_drain_url(self) -> str:
        """Gets the syslog_drain_url of this ServiceBindingResponse.


        :return: The syslog_drain_url of this ServiceBindingResponse.
        :rtype: str
        """
        return self._syslog_drain_url

    @syslog_drain_url.setter
    def syslog_drain_url(self, syslog_drain_url: str):
        """Sets the syslog_drain_url of this ServiceBindingResponse.


        :param syslog_drain_url: The syslog_drain_url of this ServiceBindingResponse.
        :type syslog_drain_url: str
        """

        self._syslog_drain_url = syslog_drain_url

    @property
    def route_service_url(self) -> str:
        """Gets the route_service_url of this ServiceBindingResponse.


        :return: The route_service_url of this ServiceBindingResponse.
        :rtype: str
        """
        return self._route_service_url

    @route_service_url.setter
    def route_service_url(self, route_service_url: str):
        """Sets the route_service_url of this ServiceBindingResponse.


        :param route_service_url: The route_service_url of this ServiceBindingResponse.
        :type route_service_url: str
        """

        self._route_service_url = route_service_url

    @property
    def volume_mounts(self) -> List[ServiceBindingVolumeMount]:
        """Gets the volume_mounts of this ServiceBindingResponse.


        :return: The volume_mounts of this ServiceBindingResponse.
        :rtype: List[ServiceBindingVolumeMount]
        """
        return self._volume_mounts

    @volume_mounts.setter
    def volume_mounts(self, volume_mounts: List[ServiceBindingVolumeMount]):
        """Sets the volume_mounts of this ServiceBindingResponse.


        :param volume_mounts: The volume_mounts of this ServiceBindingResponse.
        :type volume_mounts: List[ServiceBindingVolumeMount]
        """

        self._volume_mounts = volume_mounts

    @property
    def endpoints(self) -> List[ServiceBindingEndpoint]:
        """Gets the endpoints of this ServiceBindingResponse.


        :return: The endpoints of this ServiceBindingResponse.
        :rtype: List[ServiceBindingEndpoint]
        """
        return self._endpoints

    @endpoints.setter
    def endpoints(self, endpoints: List[ServiceBindingEndpoint]):
        """Sets the endpoints of this ServiceBindingResponse.


        :param endpoints: The endpoints of this ServiceBindingResponse.
        :type endpoints: List[ServiceBindingEndpoint]
        """

        self._endpoints = endpoints
