# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.schema_parameters import SchemaParameters
from swagger_server import util


class ServiceBindingSchemaObject(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, create: SchemaParameters=None):  # noqa: E501
        """ServiceBindingSchemaObject - a model defined in Swagger

        :param create: The create of this ServiceBindingSchemaObject.  # noqa: E501
        :type create: SchemaParameters
        """
        self.swagger_types = {
            'create': SchemaParameters
        }

        self.attribute_map = {
            'create': 'create'
        }

        self._create = create

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceBindingSchemaObject':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceBindingSchemaObject of this ServiceBindingSchemaObject.  # noqa: E501
        :rtype: ServiceBindingSchemaObject
        """
        return util.deserialize_model(dikt, cls)

    @property
    def create(self) -> SchemaParameters:
        """Gets the create of this ServiceBindingSchemaObject.


        :return: The create of this ServiceBindingSchemaObject.
        :rtype: SchemaParameters
        """
        return self._create

    @create.setter
    def create(self, create: SchemaParameters):
        """Sets the create of this ServiceBindingSchemaObject.


        :param create: The create of this ServiceBindingSchemaObject.
        :type create: SchemaParameters
        """

        self._create = create
