# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.service_instance_metadata import ServiceInstanceMetadata
from swagger_server import util


class ServiceInstanceProvisionResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, dashboard_url: str=None, metadata: ServiceInstanceMetadata=None):  # noqa: E501
        """ServiceInstanceProvisionResponse - a model defined in Swagger

        :param dashboard_url: The dashboard_url of this ServiceInstanceProvisionResponse.  # noqa: E501
        :type dashboard_url: str
        :param metadata: The metadata of this ServiceInstanceProvisionResponse.  # noqa: E501
        :type metadata: ServiceInstanceMetadata
        """
        self.swagger_types = {
            'dashboard_url': str,
            'metadata': ServiceInstanceMetadata
        }

        self.attribute_map = {
            'dashboard_url': 'dashboard_url',
            'metadata': 'metadata'
        }

        self._dashboard_url = dashboard_url
        self._metadata = metadata

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceInstanceProvisionResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceInstanceProvisionResponse of this ServiceInstanceProvisionResponse.  # noqa: E501
        :rtype: ServiceInstanceProvisionResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def dashboard_url(self) -> str:
        """Gets the dashboard_url of this ServiceInstanceProvisionResponse.


        :return: The dashboard_url of this ServiceInstanceProvisionResponse.
        :rtype: str
        """
        return self._dashboard_url

    @dashboard_url.setter
    def dashboard_url(self, dashboard_url: str):
        """Sets the dashboard_url of this ServiceInstanceProvisionResponse.


        :param dashboard_url: The dashboard_url of this ServiceInstanceProvisionResponse.
        :type dashboard_url: str
        """

        self._dashboard_url = dashboard_url

    @property
    def metadata(self) -> ServiceInstanceMetadata:
        """Gets the metadata of this ServiceInstanceProvisionResponse.


        :return: The metadata of this ServiceInstanceProvisionResponse.
        :rtype: ServiceInstanceMetadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: ServiceInstanceMetadata):
        """Sets the metadata of this ServiceInstanceProvisionResponse.


        :param metadata: The metadata of this ServiceInstanceProvisionResponse.
        :type metadata: ServiceInstanceMetadata
        """

        self._metadata = metadata
