# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ServiceInstanceMetadata(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, labels: object=None, attributes: object=None):  # noqa: E501
        """ServiceInstanceMetadata - a model defined in Swagger

        :param labels: The labels of this ServiceInstanceMetadata.  # noqa: E501
        :type labels: object
        :param attributes: The attributes of this ServiceInstanceMetadata.  # noqa: E501
        :type attributes: object
        """
        self.swagger_types = {
            'labels': object,
            'attributes': object
        }

        self.attribute_map = {
            'labels': 'labels',
            'attributes': 'attributes'
        }

        self._labels = labels
        self._attributes = attributes

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceInstanceMetadata':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceInstanceMetadata of this ServiceInstanceMetadata.  # noqa: E501
        :rtype: ServiceInstanceMetadata
        """
        return util.deserialize_model(dikt, cls)

    @property
    def labels(self) -> object:
        """Gets the labels of this ServiceInstanceMetadata.


        :return: The labels of this ServiceInstanceMetadata.
        :rtype: object
        """
        return self._labels

    @labels.setter
    def labels(self, labels: object):
        """Sets the labels of this ServiceInstanceMetadata.


        :param labels: The labels of this ServiceInstanceMetadata.
        :type labels: object
        """

        self._labels = labels

    @property
    def attributes(self) -> object:
        """Gets the attributes of this ServiceInstanceMetadata.


        :return: The attributes of this ServiceInstanceMetadata.
        :rtype: object
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes: object):
        """Sets the attributes of this ServiceInstanceMetadata.


        :param attributes: The attributes of this ServiceInstanceMetadata.
        :type attributes: object
        """

        self._attributes = attributes
